name: Web App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies, lint, build, and test
        run: npm ci
      - name: Lint
        run: npx ng lint
      - name: Build
        run: npx ng build --configuration production
      - name: Test
        run: npx ng test --watch=false --coverage
